---
- name: PgBouncer Setup
  gather_facts: false
  hosts: all
  tasks:
     - name: Transfering PgBouncer install script
       copy: src=pgbouncer/pgbouncer_install.sh dest=/tmp mode=0777

     - name: Transfering PgBouncer configuration script
       copy: src=pgbouncer/pgbouncer_config.sh dest=/tmp mode=0777

     - name: Executing PgBouncer install script
       command: "sh /tmp/pgbouncer_install.sh {{ postgresql_version }}"
       register: cmd_install
     - debug: msg="{{ cmd_install.stdout_lines|replace('\\t',' ') }}"
     - debug: msg="{{ cmd_install.stderr_lines|replace('\\t',' ') }}"

     - name: Executing PgBouncer install script
       command: "sh /tmp/pgbouncer_config.sh"
       register: cmd_config
     - debug: msg="{{ cmd_config.stdout_lines|replace('\\t',' ') }}"
     - debug: msg="{{ cmd_config.stderr_lines|replace('\\t',' ') }}"

     - name: Removing - PgBouncer install script
       file:
         path: /tmp/pgbouncer_install.sh
         state: absent

     - name: Removing - PgBouncer configuration script
       file:
         path: /tmp/pgbouncer_config.sh
         state: absent
